-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 19:45:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`authors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `Author ID` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL,
  PRIMARY KEY (`Author ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `Book ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `authors_Author ID` INT NOT NULL,
  PRIMARY KEY (`Book ID`, `authors_Author ID`),
  INDEX `fk_books_authors_idx` (`authors_Author ID` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors`
    FOREIGN KEY (`authors_Author ID`)
    REFERENCES `mydb`.`authors` (`Author ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `User ID` INT NOT NULL AUTO_INCREMENT,
  `First name` VARCHAR(45) NULL,
  `Last name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`User ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favorites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `users_User ID` INT NOT NULL,
  `books_Book ID` INT NOT NULL,
  `books_authors_Author ID` INT NOT NULL,
  INDEX `fk_users_has_books_books1_idx` (`books_Book ID` ASC, `books_authors_Author ID` ASC) VISIBLE,
  INDEX `fk_users_has_books_users1_idx` (`users_User ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_books_users1`
    FOREIGN KEY (`users_User ID`)
    REFERENCES `mydb`.`users` (`User ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`books_Book ID` , `books_authors_Author ID`)
    REFERENCES `mydb`.`books` (`Book ID` , `authors_Author ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
